dadaBaseUrl: 'windows.crabapples.cn'
dataBaseParam: 'useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull'
dataBaseDriveV8: 'com.mysql.cj.jdbc.Driver'
dataBaseDriveV5: 'com.mysql.jdbc.Driver'
isDebug: true

spring :
  datasource:
    driverClassName: ${dataBaseDriveV8} #数据库驱动
    url: jdbc:mysql://${dadaBaseUrl}:3306/learn?useSSL=false&${dataBaseParam} #数据库地址
    username: learn #数据库用户名
    password: learn #数据库密码
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driverClassName: com.mysql.jdbc.Driver
