server:
  port: 9090

spring :
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.9.18:3306/he-study?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    password: demo
    username: demo
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driverClassName: com.mysql.jdbc.Driver
  jpa:
    #是否在控制台显示数据库语句
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html