aesKey: "crabapples"
server:
  port: 9090 #启动端口
#  servlet:
#    context-path: /learn #应用名

spring :
  profiles:
    active: dev #激活的配置文件
  jpa:
    show-sql: true #是否在控制台显示数据库语句
    hibernate:
      ddl-auto: update #每次启动时如何操作对应表
    database-platform: org.hibernate.dialect.MySQL8Dialect #设置jpa方言为mysql
  thymeleaf:
    prefix: classpath:templates/ #thymeleaf模板引擎路径
#    suffix: .html #thymeleaf模板后缀
  mvc:
    static-path-pattern: /static/** #静态资源访问路径
  resources:
    static-locations: classpath:/static/** #静态资源映射路径

logging:
  pattern:
    level: info
