version: "3"
#version: "3.9"
#version: "2.3"
# 创建网络
networks:
  redis_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.21.0/24
#          gateway: 172.16.21.1
# 创建服务
services:
  redis_sentinel:
    networks:
      redis_network:
        ipv4_address: 172.16.21.5
    container_name: redis_sentinel
    image: bitnami/redis-sentinel:latest
    restart: always
    volumes:
      - /data/redis/conf:/usr/local/etc/redis
    ports:
      - "26380:26379"
    environment:
      - REDIS_MASTER_HOST=redis_6380
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_SENTINEL_QUORUM=1
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=3000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=15000
    depends_on:
      - redis_6380
      - redis_6381
      - redis_6382

  redis_6380:
    networks:
      redis_network:
        ipv4_address: 172.16.21.2
    container_name: redis_6380
    image: harbor.crabapples.cn/redis/redis:latest
    restart: always
    volumes:
      - /data/redis/conf:/usr/local/etc/redis
    ports:
      - "6380:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_6380.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3

  redis_6381:
    networks:
      redis_network:
        ipv4_address: 172.16.21.3
    container_name: redis_6381
    image: harbor.crabapples.cn/redis/redis:latest
    restart: always
    volumes:
      - /data/redis/conf:/usr/local/etc/redis
    ports:
      - "6381:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_6381.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6380

  redis_6382:
    networks:
      redis_network:
        ipv4_address: 172.16.21.4
    container_name: redis_6382
    image: harbor.crabapples.cn/redis/redis:latest
    restart: always
    volumes:
      - /data/redis/conf:/usr/local/etc/redis
    ports:
      - "6382:6379"
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis_6382.conf"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis_6380
