crabapples:
  AES_KEY: crabapples
  REDIS_PREFIX: crabapples
  TOKEN_CACHE_TIME: 30
  SALT: crabapples
mail:
  host: smtp.qq.com
  source: xxxxx@qq.com
  port: 465
  username: xxxxx@qq.com
  password: xxxxx
  isAuth: true
  isDebug: true
  protocol: smtp
  socketFactory: javax.net.ssl.SSLSocketFactory
turing:
  url: http://openapi.tuling123.com/openapi/api/v2
  appKey: 67e51f0bc2864cdc8256f24dadf218f8

